import { Association } from './associations'
import { Dish, Facet } from './types'

// The library of what this kitchen can cook, and what it knows about food itself.
//
// Pure data. Every dish carries its Hindi name, its ingredients in the units the
// cook actually uses, and — where it is a dish rather than an accompaniment — the
// method in Hindi. The method is written down rather than generated because it
// ends up in the hands of someone who will act on it: a quantity nobody wrote is
// a quantity nobody checked.
//
// Nutrition is estimated, good to roughly ±20%, and exists to support
// lighter/ordinary/heavier — never a number on a screen.

// Frozen on purpose. Rotation and balance arithmetic breaks silently the moment
// 'light' is also spelled 'lite', 'halka' and 'easy on stomach'. Additions wait
// for approval; they are rare and worth a tap.
export const FACETS: Facet[] = [
  'light', 'easy-to-digest', 'heavy', 'rich', 'fried', 'cheat-meal',
  'protein-rich', 'high-fibre', 'carb-led', 'gravy', 'dry',
  'one-pot', 'quick', 'mild', 'comfort', 'leafy', 'curd-based',
  'festive', 'breakfast-ish', 'south-indian',
]

const ADDED = Date.parse('2026-08-01T00:00:00Z')

const base = { status: 'active' as const, addedAt: ADDED }
const ALL = ['ankur', 'shruti', 'krishna']
const GROWNUPS = ['ankur', 'shruti']

export const DISHES: Dish[] = [
  {
    ...base,
    id: 'khichdi',
    nameEn: 'Khichdi',
    nameHi: 'खिचड़ी',
    ingredients: [
      { item: 'rice', quantity: '2 katori' },
      { item: 'moong dal', quantity: '1 katori' },
      { item: 'haldi', quantity: 'chutki bhar' },
      { item: 'jeera', quantity: '1 chhota chammach' },
      { item: 'hing', quantity: 'chutki bhar' },
      { item: 'ghee', quantity: '2 chammach' },
      { item: 'green chilli', quantity: '2', optional: true },
      { item: 'salt' },
    ],
    facets: ['light', 'easy-to-digest', 'one-pot', 'comfort', 'carb-led', 'mild'],
    nutrition: { calories: 340, proteinG: 11, carbsG: 58, fatG: 7, fibreG: 4, estimatedFrom: 'llm' },
    effort: 1,
    servesWell: ALL,
    fork: {
      forDiner: 'krishna',
      instructionEn: "One pot — Krishna's out before the mirchi.",
      instructionHi: 'एक ही पतीला — मिर्च डालने से पहले कृष्णा की कटोरी निकाल लें',
      atStep: 4,
    },
    methodHi: [
      'दाल और चावल धोकर कुकर में डालें।',
      'हल्दी, नमक और थोड़ा घी डालकर 3–4 सीटी लगा लें।',
      'अलग से घी में जीरा और हींग का तड़का बना लें।',
      'तड़का मिलाने से पहले एक कटोरी खिचड़ी कृष्णा के लिए निकाल लें — बिना मिर्च के।',
      'बाकी खिचड़ी में तड़का और हरी मिर्च डाल दें। गरम ही परोसें।',
    ],
  },
  {
    ...base,
    id: 'rajma-chawal',
    nameEn: 'Rajma chawal',
    nameHi: 'राजमा चावल',
    ingredients: [
      { item: 'rajma', quantity: '1.5 katori' },
      { item: 'rice', quantity: '2 katori' },
      { item: 'onion', quantity: '2' },
      { item: 'tomato', quantity: '3' },
      { item: 'ginger', quantity: 'ek tukda' },
      { item: 'garlic', quantity: '6-7 kali' },
      { item: 'garam masala', quantity: '1 chhota chammach' },
      { item: 'oil', quantity: '3 chammach' },
    ],
    facets: ['heavy', 'protein-rich', 'gravy', 'comfort', 'high-fibre'],
    nutrition: { calories: 610, proteinG: 21, carbsG: 92, fatG: 15, fibreG: 13, estimatedFrom: 'llm' },
    effort: 3,
    servesWell: ALL,
    fork: {
      forDiner: 'krishna',
      instructionEn: "Krishna's bowl out before the garam masala.",
      instructionHi: 'गरम मसाला डालने से पहले कृष्णा की कटोरी अलग निकाल लें',
      atStep: 4,
    },
    methodHi: [
      'राजमा रात भर भिगोकर सुबह कुकर में नरम होने तक उबाल लें — 5–6 सीटी।',
      'प्याज़, अदरक और लहसुन बारीक काटकर तेल में सुनहरा होने तक भूनें।',
      'टमाटर डालकर तेल छूटने तक पकाएँ, फिर उबला राजमा मिला दें।',
      'गरम मसाला डालने से पहले कृष्णा की कटोरी निकाल लें।',
      'धीमी आँच पर 10 मिनट और पकाएँ। चावल अलग से बना लें।',
    ],
  },
  {
    ...base,
    id: 'poha',
    nameEn: 'Poha',
    nameHi: 'पोहा',
    ingredients: [
      { item: 'poha', quantity: '3 katori' },
      { item: 'onion', quantity: '1' },
      { item: 'potato', quantity: '1', optional: true },
      { item: 'mustard seeds', quantity: '1 chhota chammach' },
      { item: 'green chilli', quantity: '2' },
      { item: 'haldi', quantity: 'chutki bhar' },
      { item: 'oil', quantity: '2 chammach' },
      { item: 'lemon', quantity: '1', optional: true },
    ],
    facets: ['light', 'quick', 'breakfast-ish', 'carb-led'],
    nutrition: { calories: 280, proteinG: 6, carbsG: 48, fatG: 7, fibreG: 3, estimatedFrom: 'llm' },
    effort: 1,
    servesWell: ALL,
    methodHi: [
      'पोहा छलनी में धोकर 5 मिनट छोड़ दें।',
      'तेल में राई, हरी मिर्च और प्याज़ भूनें, फिर हल्दी और नमक डालें।',
      'पोहा मिलाकर ढककर 3–4 मिनट भाप पर रखें। ऊपर से नींबू निचोड़ दें।',
    ],
  },
  {
    ...base,
    id: 'bhindi-masala',
    nameEn: 'Bhindi masala',
    nameHi: 'भिंडी मसाला',
    ingredients: [
      { item: 'bhindi', quantity: 'aadha kilo' },
      { item: 'onion', quantity: '2' },
      { item: 'tomato', quantity: '1' },
      { item: 'dhania', quantity: '1 chhota chammach' },
      { item: 'amchur', quantity: 'chutki bhar' },
      { item: 'oil', quantity: '3 chammach' },
      { item: 'salt' },
    ],
    facets: ['dry', 'high-fibre', 'light'],
    nutrition: { calories: 190, proteinG: 4, carbsG: 16, fatG: 12, fibreG: 6, estimatedFrom: 'llm' },
    effort: 2,
    servesWell: ALL,
    methodHi: [
      'भिंडी धोकर अच्छी तरह सुखा लें, फिर गोल टुकड़ों में काटें।',
      'तेज़ आँच पर तेल में भिंडी को बिना ढके भूनें ताकि लस न आए।',
      'प्याज़ और टमाटर डालकर मसाले मिलाएँ, आख़िर में अमचूर डालें।',
    ],
  },
  {
    ...base,
    id: 'dal-tadka',
    nameEn: 'Dal tadka',
    nameHi: 'दाल तड़का',
    ingredients: [
      { item: 'toor dal', quantity: '1.5 katori' },
      { item: 'tomato', quantity: '1' },
      { item: 'garlic', quantity: '5-6 kali' },
      { item: 'jeera', quantity: '1 chhota chammach' },
      { item: 'haldi', quantity: 'chutki bhar' },
      { item: 'ghee', quantity: '2 chammach' },
      { item: 'green chilli', quantity: '2', optional: true },
    ],
    facets: ['protein-rich', 'comfort', 'light', 'gravy'],
    nutrition: { calories: 260, proteinG: 14, carbsG: 34, fatG: 8, fibreG: 8, estimatedFrom: 'llm' },
    effort: 2,
    servesWell: ALL,
    fork: {
      forDiner: 'krishna',
      instructionEn: "Set his dal aside before the chilli goes in.",
      instructionHi: 'मिर्च डालने से पहले कृष्णा की दाल अलग निकाल लें',
      atStep: 3,
    },
    methodHi: [
      'दाल हल्दी और नमक के साथ कुकर में 3 सीटी तक पकाएँ।',
      'घी में जीरा, लहसुन और टमाटर का तड़का बनाएँ।',
      'तड़के में हरी मिर्च डालने से पहले कृष्णा की दाल अलग निकाल लें।',
      'बाकी दाल में तड़का मिला दें।',
    ],
  },
  {
    ...base,
    id: 'aloo-paratha',
    nameEn: 'Aloo paratha',
    nameHi: 'आलू पराठा',
    ingredients: [
      { item: 'atta', quantity: '3 katori' },
      { item: 'potato', quantity: 'aadha kilo' },
      { item: 'onion', quantity: '1', optional: true },
      { item: 'green chilli', quantity: '2', optional: true },
      { item: 'dhania', quantity: '1 chhota chammach' },
      { item: 'ghee', quantity: '4 chammach' },
    ],
    facets: ['heavy', 'breakfast-ish', 'comfort', 'carb-led'],
    nutrition: { calories: 520, proteinG: 11, carbsG: 74, fatG: 19, fibreG: 6, estimatedFrom: 'llm' },
    effort: 3,
    servesWell: ALL,
    fork: {
      forDiner: 'krishna',
      instructionEn: "His stuffing plain — no chilli, less masala.",
      instructionHi: 'कृष्णा की पिट्ठी सादी रखें — मिर्च नहीं, मसाला कम',
      atStep: 2,
    },
    methodHi: [
      'आटा गूँथकर आधा घंटा ढककर रख दें।',
      'आलू उबालकर मसले, मसाला मिलाएँ — कृष्णा के लिए थोड़ी पिट्ठी सादी अलग रखें।',
      'पराठे बेलकर तवे पर घी लगाकर दोनों तरफ़ सेंक लें।',
    ],
  },
  {
    ...base,
    id: 'paneer-butter-masala',
    nameEn: 'Paneer butter masala',
    nameHi: 'पनीर बटर मसाला',
    ingredients: [
      { item: 'paneer', quantity: '400 gram' },
      { item: 'tomato', quantity: '5' },
      { item: 'butter', quantity: '3 chammach' },
      { item: 'cream', quantity: 'aadha katori' },
      { item: 'kasuri methi', quantity: '1 chhota chammach' },
      { item: 'ginger', quantity: 'ek tukda' },
      { item: 'garam masala', quantity: 'chutki bhar' },
    ],
    facets: ['rich', 'protein-rich', 'gravy', 'festive', 'heavy'],
    nutrition: { calories: 560, proteinG: 22, carbsG: 20, fatG: 42, fibreG: 3, estimatedFrom: 'llm' },
    effort: 3,
    servesWell: ALL,
    methodHi: [
      'टमाटर और अदरक उबालकर पीस लें और छान लें।',
      'मक्खन में यह प्यूरी पकाएँ जब तक गाढ़ी न हो जाए।',
      'पनीर के टुकड़े, क्रीम और कसूरी मेथी डालकर 5 मिनट पकाएँ।',
    ],
  },
  {
    ...base,
    id: 'jeera-rice',
    nameEn: 'Jeera rice',
    nameHi: 'जीरा चावल',
    ingredients: [
      { item: 'rice', quantity: '2 katori' },
      { item: 'jeera', quantity: '1 chhota chammach' },
      { item: 'ghee', quantity: '1 chammach' },
      { item: 'salt' },
    ],
    facets: ['carb-led', 'quick', 'mild'],
    nutrition: { calories: 300, proteinG: 6, carbsG: 62, fatG: 4, fibreG: 1, estimatedFrom: 'llm' },
    effort: 1,
    everyday: true,
    servesWell: ALL,
    methodHi: [
      'चावल धोकर 20 मिनट भिगो दें।',
      'घी में जीरा चटकाकर चावल और दुगना पानी डालें, ढककर पकने दें।',
    ],
  },
  {
    ...base,
    id: 'roti',
    nameEn: 'Roti',
    nameHi: 'रोटी',
    ingredients: [
      { item: 'atta', quantity: '3 katori' },
      { item: 'ghee', quantity: 'thoda sa', optional: true },
      { item: 'salt', optional: true },
    ],
    facets: ['carb-led', 'quick', 'mild'],
    nutrition: { calories: 220, proteinG: 7, carbsG: 44, fatG: 3, fibreG: 5, estimatedFrom: 'llm' },
    effort: 1,
    everyday: true,
    servesWell: ALL,
    methodHi: ['आटा गूँथकर रोटियाँ बेल लें और तवे पर सेंक लें।'],
  },
  {
    ...base,
    id: 'kadhi-chawal',
    nameEn: 'Kadhi chawal',
    nameHi: 'कढ़ी चावल',
    ingredients: [
      { item: 'curd', quantity: '2 katori' },
      { item: 'besan', quantity: 'aadha katori' },
      { item: 'rice', quantity: '2 katori' },
      { item: 'mustard seeds', quantity: '1 chhota chammach' },
      { item: 'haldi', quantity: 'chutki bhar' },
      { item: 'hing', quantity: 'chutki bhar' },
      { item: 'oil', quantity: '2 chammach' },
    ],
    facets: ['curd-based', 'comfort', 'mild', 'gravy', 'protein-rich'],
    nutrition: { calories: 400, proteinG: 13, carbsG: 62, fatG: 11, fibreG: 3, estimatedFrom: 'llm' },
    effort: 2,
    servesWell: ALL,
    methodHi: [
      'दही और बेसन को पानी के साथ अच्छी तरह फेंट लें ताकि गुठली न रहे।',
      'हल्दी और नमक डालकर धीमी आँच पर आधा घंटा पकाएँ, बीच-बीच में चलाती रहें।',
      'राई और हींग का तड़का ऊपर से डाल दें। चावल के साथ परोसें।',
    ],
  },
  {
    ...base,
    id: 'chole',
    nameEn: 'Chole',
    nameHi: 'छोले',
    ingredients: [
      { item: 'chana', quantity: '1.5 katori' },
      { item: 'onion', quantity: '2' },
      { item: 'tomato', quantity: '3' },
      { item: 'ginger', quantity: 'ek tukda' },
      { item: 'chaat masala', quantity: '1 chhota chammach' },
      { item: 'garam masala', quantity: '1 chhota chammach' },
      { item: 'oil', quantity: '3 chammach' },
    ],
    facets: ['protein-rich', 'high-fibre', 'gravy', 'heavy'],
    nutrition: { calories: 430, proteinG: 18, carbsG: 56, fatG: 14, fibreG: 14, estimatedFrom: 'llm' },
    effort: 3,
    servesWell: ALL,
    methodHi: [
      'छोले रात भर भिगोकर कुकर में नरम होने तक उबालें।',
      'प्याज़, अदरक और टमाटर का मसाला भूनकर छोले मिलाएँ।',
      'गाढ़ा होने तक पकाएँ, आख़िर में चाट मसाला डालें।',
    ],
  },
  {
    ...base,
    id: 'baingan-bharta',
    nameEn: 'Baingan bharta',
    nameHi: 'बैंगन भरता',
    ingredients: [
      { item: 'baingan', quantity: '1 bada' },
      { item: 'onion', quantity: '2' },
      { item: 'tomato', quantity: '2' },
      { item: 'garlic', quantity: '5-6 kali' },
      { item: 'green chilli', quantity: '2', optional: true },
      { item: 'mustard oil', quantity: '3 chammach' },
    ],
    facets: ['dry', 'high-fibre', 'comfort'],
    nutrition: { calories: 210, proteinG: 5, carbsG: 20, fatG: 13, fibreG: 7, estimatedFrom: 'llm' },
    effort: 3,
    servesWell: GROWNUPS,
    methodHi: [
      'बैंगन को सीधी आँच पर भूनकर छिलका उतार लें और मसल लें।',
      'सरसों के तेल में लहसुन, प्याज़ और टमाटर भूनें।',
      'मसला बैंगन मिलाकर 10 मिनट पकाएँ।',
    ],
  },
  {
    ...base,
    id: 'palak-paneer',
    nameEn: 'Palak paneer',
    nameHi: 'पालक पनीर',
    ingredients: [
      { item: 'palak', quantity: 'aadha kilo' },
      { item: 'paneer', quantity: '250 gram' },
      { item: 'onion', quantity: '1' },
      { item: 'garlic', quantity: '4-5 kali' },
      { item: 'ginger', quantity: 'ek tukda' },
      { item: 'ghee', quantity: '2 chammach' },
    ],
    facets: ['protein-rich', 'leafy', 'gravy', 'high-fibre'],
    nutrition: { calories: 380, proteinG: 20, carbsG: 16, fatG: 26, fibreG: 6, estimatedFrom: 'llm' },
    effort: 3,
    servesWell: ALL,
    methodHi: [
      'पालक को उबलते पानी में 2 मिनट डालकर ठंडे पानी में निकाल लें, फिर पीस लें।',
      'घी में लहसुन, अदरक और प्याज़ भूनकर पालक की प्यूरी डालें।',
      'पनीर के टुकड़े डालकर 5 मिनट और पकाएँ।',
    ],
  },
  {
    ...base,
    id: 'upma',
    nameEn: 'Upma',
    nameHi: 'उपमा',
    ingredients: [
      { item: 'sooji', quantity: '2 katori' },
      { item: 'onion', quantity: '1' },
      { item: 'mustard seeds', quantity: '1 chhota chammach' },
      { item: 'urad dal', quantity: '1 chhota chammach' },
      { item: 'kadhi patta', quantity: 'thoda sa' },
      { item: 'ghee', quantity: '2 chammach' },
    ],
    facets: ['light', 'quick', 'breakfast-ish', 'south-indian', 'carb-led'],
    nutrition: { calories: 290, proteinG: 8, carbsG: 46, fatG: 9, fibreG: 3, estimatedFrom: 'llm' },
    effort: 1,
    servesWell: ALL,
    methodHi: [
      'सूजी को सूखे तवे पर हल्का भून लें।',
      'घी में राई, उड़द दाल, करी पत्ता और प्याज़ भूनें।',
      'तिगुना गरम पानी डालकर सूजी मिलाएँ, गाढ़ा होने तक चलाएँ।',
    ],
  },
  {
    ...base,
    id: 'idli-sambar',
    nameEn: 'Idli sambar',
    nameHi: 'इडली सांभर',
    ingredients: [
      { item: 'idli batter', quantity: '4 katori' },
      { item: 'toor dal', quantity: '1 katori' },
      { item: 'sambar powder', quantity: '2 chhota chammach' },
      { item: 'lauki', quantity: '1', optional: true },
      { item: 'mustard seeds', quantity: '1 chhota chammach' },
      { item: 'kadhi patta', quantity: 'thoda sa' },
    ],
    facets: ['light', 'south-indian', 'protein-rich', 'easy-to-digest'],
    nutrition: { calories: 330, proteinG: 13, carbsG: 58, fatG: 5, fibreG: 7, estimatedFrom: 'llm' },
    effort: 2,
    servesWell: ALL,
    methodHi: [
      'इडली के साँचे में घोल डालकर 12 मिनट भाप में पकाएँ।',
      'दाल उबालकर सांभर मसाला और सब्ज़ी के साथ पकाएँ।',
      'राई और करी पत्ते का तड़का लगा दें।',
    ],
  },
  {
    ...base,
    id: 'masala-dosa',
    nameEn: 'Masala dosa',
    nameHi: 'मसाला डोसा',
    ingredients: [
      { item: 'dosa batter', quantity: '4 katori' },
      { item: 'potato', quantity: 'aadha kilo' },
      { item: 'onion', quantity: '2' },
      { item: 'mustard seeds', quantity: '1 chhota chammach' },
      { item: 'haldi', quantity: 'chutki bhar' },
      { item: 'oil', quantity: '4 chammach' },
    ],
    facets: ['south-indian', 'carb-led', 'comfort', 'dry'],
    nutrition: { calories: 450, proteinG: 9, carbsG: 72, fatG: 14, fibreG: 5, estimatedFrom: 'llm' },
    effort: 4,
    servesWell: ALL,
    methodHi: [
      'आलू उबालकर राई, प्याज़ और हल्दी के साथ भुरजी बना लें।',
      'तवा गरम करके पतला डोसा फैलाएँ, किनारों पर तेल लगाएँ।',
      'बीच में आलू भरकर मोड़ लें।',
    ],
  },
  {
    ...base,
    id: 'lauki-chana-dal',
    nameEn: 'Lauki chana dal',
    nameHi: 'लौकी चना दाल',
    ingredients: [
      { item: 'lauki', quantity: '1' },
      { item: 'chana dal', quantity: '1 katori' },
      { item: 'tomato', quantity: '1' },
      { item: 'jeera', quantity: '1 chhota chammach' },
      { item: 'haldi', quantity: 'chutki bhar' },
      { item: 'ghee', quantity: '1 chammach' },
    ],
    facets: ['light', 'protein-rich', 'gravy', 'easy-to-digest', 'high-fibre'],
    nutrition: { calories: 250, proteinG: 12, carbsG: 34, fatG: 6, fibreG: 9, estimatedFrom: 'llm' },
    effort: 2,
    servesWell: ALL,
    methodHi: [
      'चना दाल आधा घंटा भिगो दें।',
      'लौकी काटकर दाल के साथ कुकर में हल्दी और नमक डालकर 3 सीटी लगाएँ।',
      'घी में जीरे का तड़का लगाकर मिला दें।',
    ],
  },
  {
    ...base,
    id: 'veg-pulao',
    nameEn: 'Veg pulao',
    nameHi: 'वेज पुलाव',
    ingredients: [
      { item: 'rice', quantity: '2 katori' },
      { item: 'peas', quantity: '1 katori' },
      { item: 'cauliflower', quantity: 'aadha' },
      { item: 'onion', quantity: '1' },
      { item: 'garam masala', quantity: '1 chhota chammach' },
      { item: 'ghee', quantity: '2 chammach' },
    ],
    facets: ['one-pot', 'carb-led', 'quick', 'comfort'],
    nutrition: { calories: 380, proteinG: 9, carbsG: 66, fatG: 9, fibreG: 6, estimatedFrom: 'llm' },
    effort: 2,
    servesWell: ALL,
    methodHi: [
      'घी में प्याज़ और सब्ज़ियाँ भूनें।',
      'भीगे चावल और दुगना पानी डालकर ढककर पकाएँ।',
    ],
  },
  {
    ...base,
    id: 'besan-chilla',
    nameEn: 'Besan chilla',
    nameHi: 'बेसन चीला',
    ingredients: [
      { item: 'besan', quantity: '2 katori' },
      { item: 'onion', quantity: '1' },
      { item: 'tomato', quantity: '1' },
      { item: 'green chilli', quantity: '1', optional: true },
      { item: 'haldi', quantity: 'chutki bhar' },
      { item: 'oil', quantity: '2 chammach' },
    ],
    facets: ['protein-rich', 'light', 'quick', 'breakfast-ish'],
    nutrition: { calories: 270, proteinG: 14, carbsG: 30, fatG: 10, fibreG: 6, estimatedFrom: 'llm' },
    effort: 1,
    servesWell: ALL,
    fork: {
      forDiner: 'krishna',
      instructionEn: "His chilla without the chilli.",
      instructionHi: 'कृष्णा का चीला बिना मिर्च के बना दें',
      atStep: 1,
    },
    methodHi: [
      'बेसन में पानी, हल्दी और नमक मिलाकर घोल बना लें — कृष्णा के लिए थोड़ा घोल बिना मिर्च का अलग रखें।',
      'प्याज़ और टमाटर बारीक काटकर घोल में मिलाएँ।',
      'तवे पर पतला फैलाकर दोनों तरफ़ सेंक लें।',
    ],
  },
  {
    ...base,
    id: 'pav-bhaji',
    nameEn: 'Pav bhaji',
    nameHi: 'पाव भाजी',
    ingredients: [
      { item: 'pav', quantity: '8' },
      { item: 'potato', quantity: 'aadha kilo' },
      { item: 'capsicum', quantity: '2' },
      { item: 'peas', quantity: '1 katori' },
      { item: 'butter', quantity: '4 chammach' },
      { item: 'tomato', quantity: '4' },
    ],
    facets: ['rich', 'heavy', 'cheat-meal', 'comfort'],
    nutrition: { calories: 640, proteinG: 13, carbsG: 82, fatG: 28, fibreG: 9, estimatedFrom: 'llm' },
    effort: 3,
    servesWell: ALL,
    methodHi: [
      'सब्ज़ियाँ उबालकर मसल लें।',
      'मक्खन में टमाटर और मसाला भूनकर सब्ज़ी मिलाएँ, अच्छी तरह घोंटें।',
      'पाव को मक्खन लगाकर तवे पर सेंक लें।',
    ],
  },
  {
    ...base,
    id: 'chai',
    nameEn: 'Chai',
    nameHi: 'चाय',
    ingredients: [
      { item: 'milk', quantity: '2 katori' },
      { item: 'sugar', quantity: '2 chhota chammach' },
      { item: 'ginger', quantity: 'thoda sa', optional: true },
    ],
    facets: ['quick', 'breakfast-ish', 'comfort'],
    nutrition: { calories: 90, proteinG: 3, carbsG: 12, fatG: 3, fibreG: 0, estimatedFrom: 'llm' },
    effort: 1,
    everyday: true,
    servesWell: GROWNUPS,
    methodHi: ['दूध, चायपत्ती और चीनी उबालकर छान लें।'],
  },
  {
    ...base,
    id: 'kachumber',
    nameEn: 'Kachumber',
    nameHi: 'कचुम्बर',
    ingredients: [
      { item: 'cucumber', quantity: '2' },
      { item: 'tomato', quantity: '2' },
      { item: 'onion', quantity: '1' },
      { item: 'lemon', quantity: '1' },
      { item: 'salt' },
    ],
    facets: ['light', 'high-fibre', 'quick', 'dry'],
    nutrition: { calories: 60, proteinG: 2, carbsG: 11, fatG: 1, fibreG: 3, estimatedFrom: 'llm' },
    effort: 1,
    servesWell: ALL,
    methodHi: ['खीरा, टमाटर और प्याज़ बारीक काटकर नमक और नींबू मिला दें।'],
  },
  {
    ...base,
    id: 'curd',
    nameEn: 'Curd',
    nameHi: 'दही',
    ingredients: [{ item: 'curd', quantity: '2 katori' }],
    facets: ['light', 'protein-rich', 'curd-based', 'easy-to-digest', 'quick'],
    nutrition: { calories: 110, proteinG: 8, carbsG: 9, fatG: 5, fibreG: 0, estimatedFrom: 'llm' },
    effort: 1,
    everyday: true,
    servesWell: ALL,
    methodHi: ['दही फेंटकर ठंडा परोसें।'],
  },
  {
    ...base,
    id: 'papad',
    nameEn: 'Papad',
    nameHi: 'पापड़',
    ingredients: [{ item: 'papad', quantity: '4' }],
    facets: ['quick', 'dry'],
    nutrition: { calories: 70, proteinG: 3, carbsG: 11, fatG: 1, fibreG: 1, estimatedFrom: 'llm' },
    effort: 1,
    everyday: true,
    servesWell: ALL,
    methodHi: ['पापड़ सेंक लें — तला नहीं।'],
  },
]

export const DISH_BY_ID: Record<string, Dish> = Object.fromEntries(
  DISHES.map(d => [d.id, d])
)

// What the system knows about food itself, as opposed to about this household.
// 'general' means assumed rather than learned here — these get corrected or borne
// out by what actually happens, which is how an assumption becomes theirs.
// Named once so the sharing is visible rather than repeated five times and
// quietly diverging.
const CARBS = ['roti', 'rice', 'khichdi', 'paratha', 'idli', 'dosa']

export const ASSOCIATIONS: Association[] = [
  {
    id: 'rice-needs-wet',
    kind: 'needs',
    subject: 'rice',
    objects: ['dal', 'kadhi', 'rajma', 'chole', 'curd', 'sambar'],
    source: 'general',
    confidence: 0.9,
    observedCount: 0,
    updatedAt: ADDED,
  },
  {
    id: 'khichdi-goes-with',
    kind: 'goes-with',
    subject: 'khichdi',
    objects: ['curd', 'papad', 'achar'],
    source: 'general',
    confidence: 0.8,
    observedCount: 0,
    updatedAt: ADDED,
  },
  {
    id: 'roti-needs-sabzi',
    kind: 'needs',
    subject: 'roti',
    objects: ['dal', 'bhindi', 'palak', 'baingan', 'chole', 'lauki', 'paneer'],
    source: 'general',
    confidence: 0.85,
    observedCount: 0,
    updatedAt: ADDED,
  },
  // The mirror of "rice cannot stand on its own". A dal or a sabzi on its own is
  // the same mistake pointed the other way, and until these existed a single
  // bowl of dal could be proposed as a whole dinner and nothing objected.
  //
  // These five rows share one object list, which is as close to a category as
  // this should get. If a sixth thing needs adding, or the list starts wanting a
  // name, that is the point to stop and ask rather than grow a taxonomy of meal
  // roles by accident.
  ...(['dal', 'chole', 'paneer', 'bhindi', 'baingan'] as const).map(subject => ({
    id: `${subject}-needs-something-to-eat-it-with`,
    kind: 'needs' as const,
    subject,
    objects: CARBS,
    source: 'general' as const,
    confidence: 0.85,
    observedCount: 0,
    updatedAt: ADDED,
  })),
  {
    id: 'roti-stands-in-for-rice',
    kind: 'stands-in-for',
    subject: 'roti',
    objects: ['rice'],
    source: 'general',
    confidence: 0.9,
    observedCount: 0,
    updatedAt: ADDED,
  },
]
